manual_dict = {
    "加料时长": "Durée d'alimentation: ",
    "温度": "Température: ",
    "速度": "Vitesse: ",
    "进料": "Chargement",
    "出料": "Déchargement",
    "+": "+",
    "-": "-",
    "%": " %",
    "s": " s",
    "个": " pcs",
    "频率": "Freq: ",
    "振幅": "Amp: ",
    "中文（中国)": "Chinois",
    "English":"Français",
    "动作、速度设置":"Action, Vit",
    "原点设置":"Réglage d'origine",
    "轨迹相关":"Trajectoire",
    "托盘参数":"Paramètres palette",
    "取放位置":"Pick et place",
    "柔性振盘方式":"Plateau vibrant",
    "设置":"Paramètres",
    "供料方式：":"Mode d'alimentation: ",
    "设备动作类型：":"Type d'action du robot: ",
    "相机设置":"Paramètres caméra",
    "相机设置2":"Paramètres caméra 2",
    "保存":"Sauvegarder",
    "恢复":"Récupérer",
    "单轴速度、软极限设置":"Vitesse uniaxiale, réglage limite soft",
    "XYZ软极限":"XYZ Limite soft",
    "机器人速度设置":"Réglages vit robot",
    "使用下相机":"Utilisation caméra inférieure",
    "使用放料位相机":"Utilisation caméra pos / décharg",
    "柔触切换：":"Type préhenseur: ",
    "吸盘模式":"Mode ventouse",
    "扩展设备":"Équipements d'extension: ",
    "无":"Aucun",
    "真空吸取失败限制次数":"     Nombre max d'échecs d'aspiration: ",
    "方案保存":"Enregistrer projet",
    "系统相关":"A propos du système",
    "版本信息":"Informations version",
    "视觉方案":"Schéma visualisation",
    "全局控件":"Contrôle global",
    "返回":"Retour",
    "主程序未启动，未运行":"Programme principal inactif",
    "清零":"Réinit.",
    "产量":"Production: ",
    "计数":"Nombre: ",
    "取放计时":"Temps Pick Drop: ",
    "托盘计时":"Temps Palette: ",
    "月运行秒":"Secondes/mois: ",
    "日":"Journée",
    "内托盘行":"Ligne int",
    "中托盘行":"Ligne mil",
    "外盘行":"Ligne ext",
    "外托盘行":"Ligne ext",
    "托盘层":"Couche   ",
    "Delta装盘机器人 -":"Robot Delta - MA-R1 - ",
    "打开":"Ouvrir",
    "另存为":"Enreg.S",
    "保存":"Enreg.",
    "设置":"Param.",
    "示教":"Appr.",
    "复位(&amp;R)":"&amp;Reset",
    "启动(&amp;S)":"&amp;Démarr.",
    "暂停(&amp;P)":"&amp;Pause",
    "停止(&amp;T)":"&amp;Arrêt",
    "软件重启":"Redémarrage du logiciel",
    "新开打的文件，需要重新启动软件才起作用。请点击【确定】关闭软件后，重启软件。":"Les fichiers nouvellement ouverts nécessitent un redémarrage du logiciel pour fonctionner. \nVeuillez cliquer sur OK pour fermer le logiciel et le redémarrer.",
    "确定(&amp;O)":" &amp;OK",
    "设置权限":"Configurer les autorisations",
    "请输入密码":"Veuillez saisir le mot de passe",
    "密码":"Mot de passe: ",
    "取消(&amp;C)":"&amp;Annuler",
    "机器人运行速度设置":"Réglage de la vitesse de fonctionnement du robot",
    "运行-最高速度":"Vitesse maximale: ",
    "运行-加速度":"Accélération: ",
    "R轴半径":"Rayon de l'axe R: ",
    "圆弧速度系数":"Coefficient de vitesse tangentielle: ",
    "IO操作":"E/S",
    "/":"/",
    " / ":" / ",
    "列":"Col",
    "清\n空":"R\nA\nZ",
    "清\n除":"R\nA\nZ",
    "历\n史":"H\nI\nS",
    "日\志":"L\nO\nG",
}