manual_dict = {
    "加料时长": "Feeding Duration: ",
    "温度": "Temperature: ",
    "速度": "Speed: ",
    "进料": "Loading",
    "出料": "Unloading",
    "+": "+",
    "-": "-",
    "%": " %",
    "s": " s",
    "个": " pcs",
    "频率": "Freq: ",
    "振幅": "Amp: ",
    "中文（中国)": "Chinese",
    "English": "English",
    "动作、速度设置": "Action, Spd",
    "原点设置": "Origin Setting",
    "轨迹相关": "Trajectory",
    "托盘参数": "Pallet Params",
    "取放位置": "Pick and place",
    "柔性振盘方式": "Vibrating Plate",
    "供料方式": "Feeding Mode: ",
    "设备动作类型": "Robot Action Type: ",
    "相机设置": "Camera Settings",
    "相机设置2": "Camera Settings 2",
    "保存": "Save",
    "恢复": "Restore",
    "单轴速度、软极限设置": "Uniaxial Speed, Soft Limit Setting",
    "XYZ软极限": "XYZ Soft Limit",
    "机器人速度设置": "Robot Speed Settings",
    "使用下相机": "Use Bottom Camera",
    "使用放料位相机": "Use Loading/Unloading Camera",
    "柔触切换": "Gripper Type: ",
    "吸盘模式": "Suction Mode",
    "扩展设备": "Extension Equipment: ",
    "无": "None",
    "真空吸取失败限制次数": "Max Failed Suction Attempts: ",
    "方案保存": "Save Project",
    "系统相关": "About the System",
    "版本信息": "Version Information",
    "视觉方案": "Visualization Scheme",
    "全局控件": "Global Control",
    "返回": "Back",
    "主程序未启动，未运行": "Main Program Inactive, Ready to Start",
    "清零": "Reset",
    "产量": "Production: ",
    "计数": "Count: ",
    "取放计时": "Pick Drop Time: ",
    "托盘计时": "Pallet Time: ",
    "月运行秒": "Seconds/Month: ",
    "日": "Day",
    "内托盘行": "Inner Line",
    "中托盘行": "Middle Line",
    "外盘行": "Outer Line",
    "外托盘行": "Outer Line",
    "托盘层": "Layer",
    "Delta装盘机器人 -": "Delta Robot - MA-R1 - ",
    "打开": "Open",
    "另存为": "Save As",
    "保存": "Save",
    "设置": "Set",
    "示教": "Teach",
    "复位(&amp;R)": "&Reset",
    "启动(&amp;S)": "&Start",
    "暂停(&amp;P)": "&Pause",
    "停止(&amp;T)": "&Stop",
    "软件重启": "Software Restart",
    "新开打的文件，需要重新启动软件才起作用。请点击【确定】关闭软件后，重启软件。": "Newly opened files require a software restart to take effect. Please click [OK] to close the software and restart it.",
    "确定(&amp;O)": "&OK",
    "设置权限": "Set Permissions",
    "请输入密码": "Please Enter Password",
    "密码": "Password: ",
    "取消(&amp;C)": "&Cancel",
    "机器人运行速度设置": "Robot Speed Setting",
    "运行-最高速度": "Max Speed: ",
    "运行-加速度": "Acceleration: ",
    "R轴半径": "R Axis Radius: ",
    "圆弧速度系数": "Tangential Speed Coef: ",
    "IO操作": "I/O",
    "/": "/",
    " / ": " / ",
    "列": "Col",
    "清\n空": "C\nL\nR",
    "清\n除": "C\nL\nR",
    "历\n史": "H\nI\nS",
    "日\n志": "L\nO\nG",
    "当前轴： M1 轴": "Current Axis: M1 Axis",
    "当前轴： M2 轴": "Current Axis: M2 Axis",
    "当前轴： M3 轴": "Current Axis: M3 Axis",
    "当前轴： M4 轴": "Current Axis: M4 Axis",
    "当前轴： M5 轴": "Current Axis: M5 Axis",
    "当前轴： M6 轴": "Current Axis: M6 Axis",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "23": "23",
    "24": "24",
    "25": "25",
    "26": "26",
    "27": "27",
    "28": "28",
    "29": "29",
    "30": "30",
    "31": "31",
    "32": "32",
    "33": "33",
    "34": "34",
    "35": "35",
    "柔性振盘动作流程": "Vibrating Plate (VP) Parameters",
    "振盘动作组合": "VP Movement Combination",
    "动作类型": "Action Type: ",
    "持续时长": "Duration",
    "动作设置": "Parameters",
    "写入": "Save",
    "运行": "Run",
    "注\n数据更改后，需要先【写入】，然后才能够执行【背光开】、【背光关】、以及【运行】等动作。": "Note:\nAfter modifying the data, you need to [Save] first before you can execute actions such as [Light ON], [Light OFF], and [Run].",
    "光源开": "Light ON",
    "光源关": "Light OFF",
    "2#柔振": "2# Vib",
    "ms": " ms",
    "mm": " mm",
    "mm/s": " mm/s",
    "mm/ss": " mm/ss",
    "散开": "Disperse",
    "横": "Horizontal",
    "竖": "Vertical",
    "左": "Left",
    "下": "Down",
    "上": "Up",
    "右": "Right",
    "动作设置 - 散开": "Action - Disperse",
    "动作设置 - 右上": "Action - Up Right",
    "动作设置 - 右下<": "Action - Down Right",
    "动作设置 - 左上": "Action - Up Left",
    "动作设置 - 左下": "Action - Down Left",
    "动作设置 - 上": "Action - Up",
    "动作设置 - 下": "Action - Down",
    "动作设置 - 右": "Action - Right",
    "动作设置 - 竖": "Action - Vertical",
    "动作设置 - 左": "Action - Left",
    "动作设置 - 横": "Action - Horizontal",
    "2#柔性振盘动作流程": "2# Vib Action Group",
    "使用2#振盘": "Use 2# Vib",
    "开启振动": "Vibration ON",
    "关闭振动": "Vibration OFF",
    "振盘单一动作设置": "Single Action Settings VP",
    "柔抓外夹模式": "External Clamp Mode",
    "柔抓内撑模式": "Internal Support Mode",
    "兼容模式": "Compatibility Mode",
    "上相机设置": "Upper Camera Settings",
    "相机坐标系": "Camera Coordinate System",
    "动作类型 - ": "Action Type - ",
    "左上": "Top Left",
    "左下": "Bottom Left",
    "右上": "Top Right",
    "右下": "Bottom Right",
    "次": " Times",
    "摆盘": "Simple Palletizing",
    "分拣": "Sorting",
    "连机": "Connected Machine",
    "自由托盘": "Free Placement",
    "自由摆盘": "Free Placement",
    "多种物料摆盘": "Palletizing Multiple Types",
    "CAD摆盘": "CAD Palletizing",
    "日志": "Log",
    "关闭": "Close",
    "亮度": "Brightness: ",
    "移动到拍照位置": "Move to Capture Position",
    "拍摄": "Capture",
    "确定": "OK",
    "完成(&amp;F)": "&Finish",
    "完成": "Finish",
    "错误": "Error",
    "身份": "User: ",
    "进入": "Enter",
    "限制值设置": "Limit Configuration",
    "阴影 &lt; 加料面积则加料": "Shadow &lt; Feeding Area",
    "加料面积": "Feeding Area: ",
    "1#料仓控制": "1# Hopper",
    "2#料仓控制": "2# Hopper",
    "Blob设置": "Blob Settings",
    "不良位置": "Bad Position",
    "使用振盘阴影检测": "Use Vibration Shadow Detection",
    "振盘阴影检测": "Vibration Shadow Detection",
    "Blob面积结果": "Blob Area Result",
    "Blob阴影面积总值为： %1\n点击【是】将面积值写入到【加料面积】中。": "The total value of the Blob shadow area is: %1\nClick [Yes] to write the area value to the [Feeding Area].",
    "是": "Yes",
    "模版编号": "Template Number: ",
    "物料模版编号": "Material Template Number",
    "否": "No",
    "料仓设置": "Hopper Settings",
    "使用料仓": "Use Hopper",
    "类型": "Type",
    "IO料仓": "I/O Hopper",
    "客制料仓": "Custom Hopper",
    "加料时长": "Feeding Duration: ",
    "加料条件": "Feeding Condition: ",
    "吹气前延时": "Delay Before Vibration",
    "吹气后延时": "Delay After Vibration",
    "识别数&lt; ": "Number &lt; ",
    "开机复位": "Reset on Startup",
    "移动到待机位置": "Move to Standby Position",
    "复位后到待机位置": "Standby Position After Reset",
    "复位周期": "Reset Period",
    "各轴偏移量": "Axis Offset",
    "M1": "M1: ",
    "M2": "M2: ",
    "M3": "M3: ",
    "M1 轴：": "M1: ",
    "M2 轴：": "M2: ",
    "M3 轴：": "M3: ",
    "修改数值": "Modify Value",
    "R轴有原点开关": "The R-axis is equipped with an origin switch.",
    "轨迹参数": "Trajectory Parameters",
    "半径": "Radius: ",
    "振后延时": "Post-Vibration Delay: ",
    "放料后平移": "Horizontal Displacement After Placement",
    "X方向距离": "Distance X: ",
    "Y方向距离": "Distance Y: ",
    "取放模式": "Pick/Place Parameters",
    "放料许可": "Placement Permit",
    "R轴可以旋转360°": "R-axis 360° Rotation",
    "料满直接启动": "Start Directly When Full",
    "开机托盘清空": "Empty Tray on Startup",
    "真空检测": "Vacuum Check",
    "延迟时间": "Delay: ",
    "吸取失败时重新拍照": "Recapture on Failure",
    "待机位置": "Standby Position",
    "Goto": "Go to",
    "吸取不良放置位置": "NG Position",
    "吸咀清理时长": "Nozzle Cleaning Duration: ",
    "抓取设置": "Pickup Settings",
    "释放设置": "Release Settings",
    "抓取延时": "Pickup Delay",
    "释放动作延时": "Release Action Delay",
    "抓取缓冲": "Pickup Buffer",
    "释放缓冲": "Release Buffer",
    "距离": "Distance: ",
    "速度": "Speed: ",
    "不提前放料": "Do Not Release in Advance",
    "接用户信号释放": "Release on User Signal",
    "取放模式": "Pick/Place Mode",
    "使用破真空": "Use Blow-off on Release",
    "附加延时": "Additional Delay: ",
    "真空夹抓逻辑取反": "Invert Y0 Logic",
    "一抓一拍": "Capture on Each Pickup",
    "拍照延时": "Capture Delay",
    "取放料模式设置": "Pick and Place Mode Settings",
    "放料托盘坐标系": "Placement Coordinates",
    "自由摆盘外盘": "External Pallet",
    "中层托盘": "Middle Pallet",
    "内层托盘": "Inner Pallet",
    "行数": "Number of Rows: ",
    "行距": "Row Spacing: ",
    "列距": "Column Spacing: ",
    "列数": "Number of Columns: ",
    "托盘放置延时": "Placement Delay",
    "层数": "Number of Layers: ",
    "层距": "Layer Spacing: ",
    "一行一列一层时输出料满信号": "Always Output Full Signal",
    "整盘时不拍照": "No Capture During Full Cycle",
    "托盘坐标系": "Pallet Coordinate System",
    "按输入口指示放料": "Placement with Signal X...",
    "X方向偏移距离": "X Direction Offset Distance: ",
    "Y方向偏移距离": "Y Direction Offset Distance: ",
    "按X20,X21,X22,X23,X24放料": "Placement with X20, X21, X22, X23, X24",
    "基本信息": "Basic Information",
    "收集用于创建托盘坐标系的基本信息，并且根据这些信息来生成托盘坐标系。": "Collect basic information for creating the pallet coordinate system and generate the coordinate system based on this information.",
    "托盘坐标系的创建采用两点法：\n1、第一点用于设置原点坐标；\n2、第二点用于设置X轴正方向。": "The pallet coordinate system is created using the two-point method:\n1. The first point is used to set the origin coordinates;\n2. The second point is used to set the positive direction of the X-axis.",
    "抓取": "Grasp",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘左下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的原点设置。": "Click the [Teach] button to open the robot teaching window.\nAdjust the robot's position to align with the placement position at the bottom left corner of the pallet.\nClick the [OK] button in the teaching window to complete the origin setting of the pallet coordinate system.",
    "托盘左下角": "Bottom Left Corner of the Pallet",
    "上一步(&amp;L)": "&Prev.",
    "下一步(&amp;N)": "&Next",
    "X轴正方向设置": "Positive X-axis Direction Setting",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘右下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的X轴正方向设置。": "Click the [Teach] button to open the robot teaching window.\nAdjust the robot's position to align with the placement position at the bottom right corner of the pallet.\nClick the [OK] button in the teaching window to complete the positive X-axis direction setting of the pallet coordinate system.",
    "托盘右下角": "Bottom Right Corner of the Pallet",
    "信息收集完成": "Information Collection Completed",
    "用于创建托盘坐标系的信息已经收集完成。\n你可以点击【完成】按钮进行坐标系的计算。\n如果需要更改某些参数，也可以点击【上一步】按钮，进行参数更改。": "The information needed to create the pallet coordinate system has been collected.\nYou can click the [Finish] button to calculate the coordinate system.\nIf you need to change some parameters, you can also click the [Previous] button to modify the parameters.",
    "注意：\n如果你在这里点击【完成】按钮对托盘坐标系进行了修改，则必然会影响到取放料的位置。因而必须重新设置取放料位置，否则会出现放料位置偏差的问题。": "Note:\nIf you click the [Finish] button here to modify the pallet coordinate system, it will inevitably affect the position of the pick and place. Therefore, you must reset the pick and place position; otherwise, there will be a deviation in the placement position.",
    "抓取动作延时": "Pickup Action Delay",
    "W(背)": "B",
    "G(上)": "H",
    "编辑": "Edit",
    "警告": "Warning",
    "绘制": "Draw",
    "硬触发": "Manual Trigger",
    "移动到识别点": "Move to Identification Point",
    "提升": "Lift",
    "放料首位置": "First Pallet Position",
    "轨迹半径": "Radius: ",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘左下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的原点设置。": "Click the [Teach] button to open the robot teaching window.\nAdjust the robot's position to align with the placement position at the bottom left corner of the pallet.\nClick the [OK] button in the teaching window to complete the origin setting of the pallet coordinate system.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第二个特征点：P2。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Click the [Teach] button to open the teaching window.\nAdjust the robot to align with the second feature point on the calibration board: P2.\nThen click the [OK] button in the teaching window to read the robot's current position.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第一个特征点：P1。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Click the [Teach] button to open the teaching window.\nAdjust the robot to align with the first feature point on the calibration board: P1.\nThen click the [OK] button in the teaching window to read the robot's current position.",
    "轻摇皮带手柄，使标定板随皮带在采样位置的基础上，继续向前移动一段距离（在保证机器人能够采样到P1点的条件下，移动尽可能远的距离）。\n点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第二个特征点：P1。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Gently shake the belt handle to move the calibration board forward a distance from the sampling position with the belt (move as far as possible while ensuring the robot can sample to point P1).\nClick the [Teach] button to open the teaching window.\nAdjust the robot to align with the second feature point on the calibration board: P1.\nThen click the [OK] button in the teaching window to read the robot's current position.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使机器人上的工件样品对准托盘最左下角的放料位置。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Click the [Teach] button to open the teaching window.\nAdjust the robot so that the workpiece sample on the robot is aligned with the discharge position at the bottom left corner of the pallet.\nThen click the [OK] button in the teaching window to read the robot's current position.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准柔性振盘上的工件样品。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Click the [Teach] button to open the teaching window.\nAdjust the robot to align with the workpiece sample on the flexible tray.\nThen click the [OK] button in the teaching window to read the robot's current position.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准再定位位置。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Click the [Teach] button to open the teaching window.\nAdjust the robot to align with the repositioning position.\nThen click the [OK] button in the teaching window to read the robot's current position.",
    "在镜头下发现 %1 个元件样品。但是系统要求只能够放置一个。\n\n请你在确保镜头下方只有一个元件样品的情况下，再次识别。": "%1 component sample found under the lens. However, the system requires that only one can be placed.\n\nPlease identify again, ensuring that there is only one component sample under the lens.",
    "图上点位编号": "Number of Points: ",
    "元件样品识别成功": "Component Sample Identification Successful",
    "元件样品识别失败": "Component Sample Identification Failed",
    "P:": "P:",
    "R:": "R:",
    "X:": "X:",
    "Y::": "Y:",
    "Z::": "Z:",
    "注：\n在每一次更换产品时，都需要进行一次取放位置的采样。": "Note:\nSampling of the pick and place position is required each time the product is changed.",
    "样品放置": "Sample Placement",
    "取料位样品识别": "Sample Identification at Pickup Position",
    "点击下面的【提升】按钮，机器人自动提升到待机位置高度。\n": "Click the [Lift] button below to automatically lift the robot to the standby position height.",
    "位置采样": "Position Sampling",
    "点击下面的【释放】按钮，吸盘或者是夹抓上的工件将会释放到托盘中。\n在释放完成后，点击【下一步】执行后续步骤。": "Click the [Release] button below to release the workpiece on the suction cup or gripper onto the pallet.\nAfter the release is complete, click [Next] to proceed to the next step.",
    "释放": "Release",
    "取放位置采样": "Pick and Place Position Sampling",
    "识别": "Identification",
    "点击【移动到识别点】按钮，机器人会移动到上一步所识别的样品位置。\n需要注意的是，在这里目标位置的Z值坐标并不是准确的。\n抓取的具体位置，你仍然可以在下一步进行设置。": "Click the [Move to Identification Point] button, and the robot will move to the sample position identified in the previous step.\nNote that the Z-coordinate of the target position is not accurate here.\nYou can still set the specific position for grasping in the next step.",
    "R": "R",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    " s": " s",
    "第": "The",
    "侧面安装": "Side Installation",
    "位号块大小": "Address Block Size: ",
    "料位个数": "Number of Filling Levels: "

}