manual_dict = {
    "加料时长": "Durata di alimentazione:",
    "温度": "Temperatura:",
    "速度": "Velocità:",
    "进料": "Caricamento pezzi",
    "出料": "Scaricamento pezzi",
    "+": "+",
    "-": "-",
    "%": "%",
    "s": " s",
    "个": " pz",
    "频率": "Freq:",
    "振幅": "Amp:",
    "中文（中国）": "Cinese",
    "English": "Italiano",
    "动作、速度设置": "Azione, Vel",
    "原点设置": "Impostazione origine",
    "轨迹相关": "Traiettoria",
    "托盘参数": "Parametri pallet",
    "取放位置": "Posizione Pick e Place",
    "柔性振盘方式": "Metodo piatto vibrante",
    "供料方式": "Modalità di alimentazione:",
    "设备动作类型": "Tipo di azione del robot:",
    "相机设置": "Impostazioni telecamera",
    "相机设置2": "Impostazioni telecamera 2",
    "保存": "Salva",
    "恢复": "Ripristina",
    "单轴速度、软极限设置": "Velocità monoasse, impostazione limite software",
    "XYZ软极限": "Limite software XYZ",
    "机器人速度设置": "Impostazioni velocità robot",
    "使用下相机": "Usa telecamera inferiore",
    "使用放料位相机": "Usa telecamera posizionamento",
    "柔触切换": "Tipo di presa:",
    "吸盘模式": "Modalità ventosa",
    "扩展设备": "Dispositivi di estensione:",
    "无": "Nessuno",
    "真空吸取失败限制次数": "Numero max di errori di aspirazione:",
    "方案保存": "Salva progetto",
    "系统相关": "Informazioni sul sistema",
    "版本信息": "Informazioni versione",
    "视觉方案": "Schema visualizzazione",
    "全局控件": "Controllo globale",
    "返回": "Indietro",
    "主程序未启动，未运行": "Programma principale inattivo, pronto per partire",
    "清零": "Reimposta",
    "产量": "Produzione:",
    "计数": "Conteggio:",
    "取放计时": "Tempo Pick e Place:",
    "托盘计时": "Tempo pallet:",
    "月运行秒": "Secondi/mese:",
    "日": "Giorno",
    "内托盘行": "Riga interna pallet",
    "中托盘行": "Riga centrale pallet",
    "外盘行": "Riga esterna pallet",
    "外托盘行": "Riga esterna pallet",
    "托盘层": "Strato pallet",
    "Delta装盘机器人 -": "Robot Delta - MA-R1 -",
    "打开": "Apri",
    "另存为": "Salva con nome",
    "保存": "Salva",
    "设置": "Imp.",
    "示教": "Inseg.",
    "复位(&amp;R)": "&Reiniz.",
    "启动(&amp;S)": "&Avvio",
    "暂停(&amp;P)": "&Pausa",
    "停止(&amp;T)": "&Arresto",
    "软件重启": "Riavvio software",
    "新开打的文件，需要重新启动软件才起作用。请点击【确定】关闭软件后，重启软件。": "I file appena aperti richiedono un riavvio del software per funzionare. Fare clic su [OK] per chiudere il software e riavviarlo.",
    "确定(&amp;O)": "&OK",
    "设置权限": "Configura autorizzazioni",
    "请输入密码": "Inserire la password",
    "密码": "Password:",
    "取消(&amp;C)": "&Annulla",
    "机器人运行速度设置": "Impostazione velocità robot",
    "运行-最高速度": "Velocità massima:",
    "运行-加速度": "Accelerazione:",
    "R轴半径": "Raggio asse R:",
    "圆弧速度系数": "Coeff. velocità tangenziale:",
    "IO操作": "I/O",
    "/": "/",
    " / ": " / ",
    "列": "Col",
    "清\n空": "S\nV\nU\nO\nT\nA",
    "清\n除": "S\nV\nU\nO\nT\nA",
    "历\n史": "S\nT\nO\nR\nI\nC\nO",
    "日\n志": "G\nI\nO\nR\nN\nA\nL\nE",
    "当前轴： M1 轴": "Asse attuale: asse M1",
    "当前轴： M2 轴": "Asse attuale: asse M2",
    "当前轴： M3 轴": "Asse attuale: asse M3",
    "当前轴： M4 轴": "Asse attuale: asse M4",
    "当前轴： M5 轴": "Asse attuale: asse M5",
    "当前轴： M6 轴": "Asse attuale: asse M6",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "23": "23",
    "24": "24",
    "25": "25",
    "26": "26",
    "27": "27",
    "28": "28",
    "29": "29",
    "30": "30",
    "31": "31",
    "32": "32",
    "33": "33",
    "34": "34",
    "35": "35",
    "柔性振盘动作流程": "Parametri piatto vibrante (PV)",
    "振盘动作组合": "Combinazione movimenti PV",
    "动作类型": "Tipo di azione:",
    "持续时长": "Durata",
    "动作设置": "Parametri",
    "写入": "Reg.",
    "运行": "Esegui",
    "注\n数据更改后，需要先【写入】，然后才能够执行【背光开】、【背光关】、以及【运行】等动作。": "Nota:\nDopo aver modificato i dati, è necessario prima [Reg.] per poter eseguire azioni come [Luce ON], [Luce OFF] e [Esegui].",
    "光源开": "Luce ON",
    "光源关": "Luce OFF",
    "2#柔振": "2# Vib",
    "ms": " ms",
    "mm": " mm",
    "mm/s": " mm/s",
    "mm/ss": " mm/ss",
    "散开": "Dispersione",
    "横": "Orizzontale",
    "竖": "Verticale",
    "左": "Sinistra",
    "下": "Basso",
    "上": "Alto",
    "右": "Destra",
    "动作设置 - 散开": "Azione - Dispersione",
    "动作设置 - 右上": "Azione - Alto Destra",
    "动作设置 - 右下": "Azione - Basso Destra",
    "动作设置 - 左上": "Azione - Alto Sinistra",
    "动作设置 - 左下": "Azione - Basso Sinistra",
    "动作设置 - 上": "Azione - Alto",
    "动作设置 - 下": "Azione - Basso",
    "动作设置 - 右": "Azione - Destra",
    "动作设置 - 竖": "Azione - Verticale",
    "动作设置 - 左": "Azione - Sinistra",
    "动作设置 - 横": "Azione - Orizzontale",
    "2#柔性振盘动作流程": "2# Vib gruppo di azione",
    "使用2#振盘": "Usa 2# Vib",
    "开启振动": "Vibrazione ON",
    "关闭振动": "Vibrazione OFF",
    "振盘单一动作设置": "Parametri azione unitaria PV",
    "柔抓外夹模式": "Modalità pinza",
    "柔抓内撑模式": "Modalità pinza interna",
    "兼容模式": "Modalità compatibilità",
    "上相机设置": "Parametri telecamera",
    "相机坐标系": "Sistema di coordinate telecamera",
    "动作类型 - ": "Tipo di azione - ",
    "左上": "Alto Sinistra",
    "左下": "Basso Sinistra",
    "右上": "Alto Destra",
    "右下": "Basso Destra",
    "次": " Volte",
    "摆盘": "Pallettizzazione semplice",
    "分拣": "Cernita",
    "连机": "Macchina connessa",
    "自由托盘": "Posizionamento libero",
    "自由摆盘": "Posizionamento libero",
    "多种物料摆盘": "Pallettizzazione di più tipi di pezzi",
    "CAD摆盘": "Pallettizzazione CAD",
    "日志": "log",
    "关闭": "Chiudi",
    "亮度": "Luminosità:",
    "移动到拍照位置": "Posizione di cattura",
    "拍摄": "Cattura",
    "确定": "OK",
    "完成(&amp;F)": "&Fine",
    "完成": "Fine",
    "错误": "Errore",
    "身份": "Utente:",
    "进入": "Entra",
    "限制值设置": "Configura limiti",
    "阴影 &lt; 加料面积则加料": "Ombra &lt; Area di alimentazione",
    "加料面积": "Area di alimentazione:",
    "1#料仓控制": "1# Silo",
    "2#料仓控制": "2# Silo",
    "Blob设置": "Impostazioni Blob",
    "不良位置": "Posizione errata",
    "使用振盘阴影检测": "Utilizzo rilevamento ombre per vibrazione",
    "振盘阴影检测": "Rilevamento ombre per vibrazione",
    "Blob面积结果": "Risultato area Blob",
    "Blob阴影面积总值为： %1\n点击【是】将面积值写入到【加料面积】中。": "Il valore totale dell'area dell'ombra del blob è: %1\nFare clic su [Sì] per salvare il valore.",
    "是": "Sì",
    "模版编号": "Numero modello:",
    "物料模版编号": "Numero template",
    "否": "No",
    "料仓设置": "Impostazioni silo",
    "使用料仓": "Usa silo",
    "类型": "Tipo",
    "IO料仓": "I/O silo",
    "客制料仓": "Silo su misura",
    "加料时长": "Durata di alimentazione:",
    "加料条件": "Condizione di alimentazione:",
    "吹气前延时": "Ritardo prima della vibrazione",
    "吹气后延时": "Ritardo dopo la vibrazione",
    "识别数&lt;": "Numero &lt;",
    "开机复位": "Reinizializzazione all'avvio",
    "移动到待机位置": "Posizione di attesa",
    "复位后到待机位置": "Posizione di attesa dopo la reinizializzazione",
    "复位周期": "Periodo di reinizializzazione",
    "各轴偏移量": "Offset",
    "M1": "M1:",
    "M2": "M2:",
    "M3": "M3:",
    "M1 轴：": "M1:",
    "M2 轴：": "M2:",
    "M3 轴：": "M3:",
    "修改数值": "Modifica valore",
    "R轴有原点开关": "L'asse R è dotato di un interruttore di origine.",
    "轨迹参数": "Parametri di tracciamento",
    "半径": "Raggio:",
    "振后延时": "Ritardo post-vibrazione:",
    "放料后平移": "Traslazione orizzontale dopo il posizionamento",
    "X方向距离": "Distanza X:",
    "Y方向距离": "Distanza Y:",
    "取放模式": "Modalità Pick/Place",
    "放料许可": "Permesso di posizionamento",
    "R轴可以旋转360°": "Rotazione asse R a 360°",
    "料满直接启动": "Avvio diretto quando pieno",
    "开机托盘清空": "Svuota il pallet all'avvio",
    "真空检测": "Controllo del vuoto",
    "延迟时间": "Tempo di ritardo:",
    "吸取失败时重新拍照": "Rifotografare in caso di fallimento",
    "待机位置": "Posizione di attesa",
    "Goto": "Vai a",
    "吸取不良放置位置": "Posizione NG",
    "吸咀清理时长": "Durata pulizia ventosa:",
    "抓取设置": "Impostazioni di presa",
    "释放设置": "Impostazioni di rilascio",
    "抓取延时": "Ritardo di presa",
    "释放动作延时": "Ritardo di rilascio",
    "抓取缓冲": "Buffer di presa",
    "释放缓冲": "Buffer di rilascio",
    "距离": "Distanza:",
    "速度": "Velocità:",
    "不提前放料": "Non rilasciare in anticipo",
    "接用户信号释放": "Rilasciare su segnale utente",
    "取放模式": "Modalità Pick/Place",
    "使用破真空": "Uso di rottura del vuoto",
    "附加延时": "Ritardo aggiuntivo:",
    "真空夹抓逻辑取反": "Inversione Y0",
    "一抓一拍": "Fotografare ad ogni presa",
    "拍照延时": "Ritardo di scatto",
    "取放料模式设置": "Impostazione modalità di presa e rilascio",
    "放料托盘坐标系": "Coordinate di posizionamento pallet",
    "自由摆盘外盘": "Pallet esterno",
    "中层托盘": "Pallet medio",
    "内层托盘": "Pallet interno",
    "行数": "Numero di righe:",
    "行距": "Distanza tra righe:",
    "列距": "Distanza tra colonne:",
    "列数": "Numero di colonne:",
    "托盘放置延时": "Ritardo di posizionamento pallet",
    "层数": "Numero di strati:",
    "层距": "Distanza tra strati:",
    "一行一列一层时输出料满信号": "Segnale sempre completo in uscita",
    "整盘时不拍照": "Nessuna foto durante un ciclo completo",
    "托盘坐标系": "Sistema di coordinate del pallet",
    "按输入口指示放料": "Posizionamento con segnale X...",
    "X方向偏移距离": "Distanza di offset direzione X:",
    "Y方向偏移距离": "Distanza di offset direzione Y:",
    "按X20,X21,X22,X23,X24放料": "Posizionamento con X20, X21, X22, X23, X24",
    "基本信息": "Informazioni di base",
    "收集用于创建托盘坐标系的基本信息，并且根据这些信息来生成托盘坐标系。": "Raccogliere le informazioni di base necessarie per creare il sistema di coordinate del pallet e generare il sistema in base a queste informazioni.",
    "托盘坐标系的创建采用两点法：\n1、第一点用于设置原点坐标；\n2、第二点用于设置X轴正方向。": "La creazione del sistema di coordinate del pallet viene effettuata utilizzando il metodo a due punti:\n1. Il primo punto viene utilizzato per impostare le coordinate dell'origine;\n2. Il secondo punto viene utilizzato per impostare la direzione positiva dell'asse X.",
    "抓取": "Prendere",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘左下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的原点设置。": "Fare clic sul pulsante [Insegna] per aprire la finestra di insegnamento del robot.\nRegolare la posizione del robot in modo che sia allineata con la posizione di scarico nell'angolo in basso a sinistra del pallet.\nFare clic sul pulsante [OK] nella finestra di insegnamento per completare l'impostazione dell'origine del sistema di coordinate del pallet.",
    "托盘左下角": "Angolo in basso a sinistra del pallet",
    "上一步(&L)": "&Prec.",
    "下一步(&N)": "&Succ.",
    "X轴正方向设置": "Impostazione della direzione positiva dell'asse X",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘右下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的X轴正方向设置。": "Fare clic sul pulsante [Insegna] per aprire la finestra di insegnamento del robot.\nRegolare la posizione del robot in modo che sia allineata con la posizione di scarico nell'angolo in basso a destra del pallet.\nFare clic sul pulsante [OK] nella finestra di insegnamento per completare l'impostazione della direzione positiva dell'asse X del sistema di coordinate del pallet.",
    "托盘右下角": "Angolo in basso a destra del pallet",
    "信息收集完成": "Raccolta informazioni completata",
    "用于创建托盘坐标系的信息已经收集完成。\n你可以点击【完成】按钮进行坐标系的计算。\n如果需要更改某些参数，也可以点击【上一步】按钮，进行参数更改。": "Le informazioni necessarie per creare il sistema di coordinate del pallet sono state raccolte.\nÈ possibile fare clic sul pulsante [Fine] per calcolare il sistema di coordinate.\nSe è necessario modificare alcuni parametri, è anche possibile fare clic sul pulsante [Prec.] per modificarli.",
    "注意：\n如果你在这里点击【完成】按钮对托盘坐标系进行了修改，则必然会影响到取放料的位置。因而必须重新设置取放料位置，否则会出现放料位置偏差的问题。": "Nota:\nSe si fa clic qui sul pulsante [Fine] per modificare il sistema di coordinate del pallet, ciò influenzerà necessariamente la posizione di presa e posizionamento. Pertanto, è necessario reimpostare la posizione di presa e posizionamento, altrimenti si verificherà un problema di offset nella posizione di posizionamento.",
    "抓取动作延时": "Ritardo azione di presa",
    "W(背)": "D ",
    "G(上)": "S ",
    "编辑": "Modifica",
    "警告": "Avviso",
    "绘制": "Disegna",
    "硬触发": "Trigger manuale",
    "移动到识别点": "Vai al punto di identificazione",
    "提升": "Sollevare il pezzo",
    "放料首位置": "Prima posizione del pallet",
    "轨迹半径": "Raggio:",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘左下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的原点设置。": "Fare clic sul pulsante [Insegna] per aprire la finestra di insegnamento del robot.\nRegolare la posizione del robot in modo che sia allineata con la posizione di scarico nell'angolo in basso a sinistra del pallet.\nFare clic sul pulsante [OK] nella finestra di insegnamento per completare l'impostazione dell'origine del sistema di coordinate del pallet.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第二个特征点：P2。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Fare clic sul pulsante [Insegna] per aprire la finestra di insegnamento.\nRegolare il robot in modo che sia allineato con il secondo punto caratteristico sulla tavola di calibrazione: P2.\nQuindi fare clic sul pulsante [OK] nella finestra di insegnamento per leggere la posizione corrente del robot.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第一个特征点：P1。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Fare clic sul pulsante [Insegna] per aprire la finestra di insegnamento.\nRegolare il robot in modo che sia allineato con il primo punto caratteristico sulla tavola di calibrazione: P1.\nQuindi fare clic sul pulsante [OK] nella finestra di insegnamento per leggere la posizione corrente del robot.",
    "轻摇皮带手柄，使标定板随皮带在采样位置的基础上，继续向前移动一段距离（在保证机器人能够采样到P1点的条件下，移动尽可能远的距离）。\n点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第二个特征点：P1。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Agitare leggermente la maniglia della cinghia in modo che la tavola di calibrazione continui a muoversi in avanti su una distanza dalla posizione di campionamento con la cinghia (spostarsi il più lontano possibile assicurandosi che il robot possa campionare per puntare P1).\nFare clic sul pulsante [Insegna] per aprire la finestra di insegnamento.\nRegolare il robot in modo che sia allineato con il secondo punto caratteristico sulla tavola di calibrazione: P1.\nQuindi fare clic sul pulsante [OK] nella finestra di insegnamento per leggere la posizione corrente del robot.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使机器人上的工件样品对准托盘最左下角的放料位置。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Fare clic sul pulsante [Insegna] per aprire la finestra di insegnamento.\nRegolare il robot in modo che il campione di pezzo sul robot sia allineato con la posizione di scarico nell'angolo in basso a sinistra del pallet.\nQuindi fare clic sul pulsante [OK] nella finestra di insegnamento per leggere la posizione corrente del robot.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准柔性振盘上的工件样品。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Fare clic sul pulsante [Insegna] per aprire la finestra di insegnamento.\nRegolare il robot in modo che sia allineato con il campione di pezzo sul piatto vibrante.\nQuindi fare clic sul pulsante [OK] nella finestra di insegnamento per leggere la posizione corrente del robot.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准再定位位置。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Fare clic sul pulsante [Insegna] per aprire la finestra di insegnamento.\nRegolare il robot in modo che sia allineato con la posizione di riposizionamento.\nQuindi fare clic sul pulsante [OK] nella finestra di insegnamento per leggere la posizione corrente del robot.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准柔性振盘上的工件样品。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Fare clic sul pulsante [Insegna] per aprire la finestra di insegnamento.\nRegolare il robot in modo che sia allineato con il campione di pezzo sul piatto vibrante.\nQuindi fare clic sul pulsante [OK] nella finestra di insegnamento per leggere la posizione corrente del robot.",
    "在镜头下发现 %1 个元件样品。但是系统要求只能够放置一个。\n\n请你在确保镜头下方只有一个元件样品的情况下，再次识别。": "Trovati %1 campioni di componenti sotto l'obiettivo. Tuttavia, il sistema richiede che possa essere posizionato solo uno.\n\nSi prega di identificare nuovamente, assicurandosi che ci sia un solo campione di componente sotto l'obiettivo.",
    "图上点位编号": "Numero di punti sul grafico:",
    "元件样品识别成功": "Identificazione del campione di componente riuscita",
    "元件样品识别失败": "Identificazione del campione di componente fallita",
    "P:": "P:",
    "R:": "R:",
    "X:": "X:",
    "Y::": "Y:",
    "Z::": "Z:",
    "注：\n在每一次更换产品时，都需要进行一次取放位置的采样。": "Nota:\nOgni volta che si cambia prodotto, è necessario eseguire un campionamento della posizione di presa e posizionamento.",
    "样品放置": "Posizionamento del campione",
    "取料位样品识别": "Identificazione del campione nella posizione di presa",
    "点击下面的【提升】按钮，机器人自动提升到待机位置高度。\n": "Fare clic sul pulsante [Sollevare] qui sotto per sollevare automaticamente il robot all'altezza della posizione di attesa.",
    "位置采样": "Campionamento della posizione",
    "点击下面的【释放】按钮，吸盘或者是夹抓上的工件将会释放到托盘中。\n在释放完成后，点击【下一步】执行后续步骤。": "Fare clic sul pulsante [Rilascia] qui sotto per rilasciare il pezzo dalla ventosa o dalla pinza sul pallet.\nDopo aver completato il rilascio, fare clic su [Succ.] per procedere al passaggio successivo.",
    "释放": "Rilascia",
    "取放位置采样": "Campionamento della posizione di presa e posizionamento",
    "识别": "Identificazione",
    "点击【移动到识别点】按钮，机器人会移动到上一步所识别的样品位置。\n需要注意的是，在这里目标位置的Z值坐标并不是准确的。\n抓取的具体位置，你仍然可以在下一步进行设置。": "Fare clic sul pulsante [Vai al punto di identificazione] per spostare il robot nella posizione del campione identificata nel passaggio precedente.\nSi noti che il valore Z della posizione di destinazione non è accurato qui.\nÈ ancora possibile impostare la posizione specifica di presa nel passaggio successivo.",
    "R": "R",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    " s": " s",
    "第": "Il",
    "侧面安装": "Installazione laterale",
    "位号块大小": "Dimensione del blocco indirizzi:",
    "料位个数": "Numero di livelli di riempimento:",
}
