manual_dict = {
    "加料时长": "Durée d'alimentation: ",
    "温度": "Température: ",
    "速度": "Vitesse: ",
    "进料": "Chargement",
    "出料": "Déchargement",
    "+": "+",
    "-": "-",
    "%": " %",
    "s": " s",
    "个": " pcs",
    "频率": "Freq: ",
    "振幅": "Amp: ",
    "中文（中国)": "Chinois",
    "English": "Français",
    "动作、速度设置": "Action, Vit",
    "原点设置": "Réglage d'origine",
    "轨迹相关": "Trajectoire",
    "托盘参数": "Paramètres palette",
    "取放位置": "Pick et place",
    "柔性振盘方式": "Plateau vibrant",
    "供料方式": "Mode d'alimentation: ",
    "设备动作类型":"Type d'action du robot: ",
    "相机设置":"Paramètres caméra",
    "相机设置2":"Paramètres caméra 2",
    "保存":"Sauvegarder",
    "恢复":"Restorer",
    "单轴速度、软极限设置":"Vitesse uniaxiale, réglage limite soft",
    "XYZ软极限":"XYZ Limite soft",
    "机器人速度设置":"Réglages vit robot",
    "使用下相机":"Utilisation caméra inférieure",
    "使用放料位相机":"Utilisation caméra pos / décharg",
    "柔触切换":"Type préhenseur: ",
    "吸盘模式":"Mode ventouse",
    "扩展设备":"Équipements d'extension: ",
    "无":"Aucun",
    "真空吸取失败限制次数":"     Nombre max d'échecs d'aspiration: ",
    "方案保存":"Enregistrer projet",
    "系统相关":"A propos du système",
    "版本信息":"Informations version",
    "视觉方案":"Schéma visualisation",
    "全局控件":"Contrôle global",
    "返回":"Retour",
    "主程序未启动，未运行":"Programme principal inactif, prêt a démarrer",
    "清零":"Réinit.",
    "产量":"Production: ",
    "计数":"Nombre: ",
    "取放计时":"Temps Pick Drop: ",
    "托盘计时":"Temps Palette:   ",
    "月运行秒":"Secondes/mois: ",
    "日":"Journée",
    "内托盘行":"Ligne int",
    "中托盘行":"Ligne mil",
    "外盘行":"Ligne ext",
    "外托盘行":"Ligne ext",
    "托盘层":"Couche   ",
    "Delta装盘机器人 -":"Robot Delta - MA-R1 - ",
    "打开":"Ouvrir",
    "另存为":"Enreg.S",
    "保存":"Enreg.",
    "设置":"Param.",
    "示教":"Appr.",
    "复位(&amp;R)":"&Réinit.",
    "启动(&amp;S)":"&Démarr.",
    "暂停(&amp;P)":"&Pause",
    "停止(&amp;T)":"&Arrêt",
    "软件重启":"Redémarrage du logiciel",
    "新开打的文件，需要重新启动软件才起作用。请点击【确定】关闭软件后，重启软件。":"Les fichiers nouvellement ouverts nécessitent un redémarrage du logiciel pour fonctionner.\nVeuillez cliquer sur [OK] pour fermer le logiciel et le redémarrer.",
    "确定(&amp;O)":" &OK",
    "设置权限":"Configurer les autorisations",
    "请输入密码":"Veuillez saisir le mot de passe",
    "密码":"Mot de passe: ",
    "取消(&amp;C)":"&Annuler",
    "机器人运行速度设置":"Réglage vitesse robot",
    "运行-最高速度":"Vitesse maximale: ",
    "运行-加速度":"Accélération: ",
    "R轴半径":"Rayon axe R: ",
    "圆弧速度系数":"Coef vitesse tangentielle: ",
    "IO操作":"E/S",
    "/":"/",
    " / ":" / ",
    "列":"Col",
    "清\n空":"R\nA\nZ",
    "清\n除":"R\nA\nZ",
    "清\n除":"R\nA\nZ",
    "历\n史":"H\nI\nS",
    "日\n志":"L\nO\nG",
    "当前轴： M1 轴":"Axe actuel : axe M1",
    "当前轴： M2 轴":"Axe actuel : axe M2",
    "当前轴： M3 轴":"Axe actuel : axe M3",
    "当前轴： M4 轴":"Axe actuel : axe M4",
    "当前轴： M5 轴":"Axe actuel : axe M5",
    "当前轴： M6 轴":"Axe actuel : axe M6",
    "1":"1",
    "2":"2",
    "3":"3",
    "4":"4",
    "5":"5",
    "6":"6",
    "7":"7",
    "8":"8",
    "9":"9",
    "10":"10",
    "11":"11",
    "12":"12",
    "13":"13",
    "14":"14",
    "15":"15",
    "16":"16",
    "17":"17",
    "18":"18",
    "19":"19",
    "20":"20",
    "21":"21",
    "22":"22",
    "23":"23",
    "24":"24",
    "25":"25",
    "26":"26",
    "27":"27",
    "28":"28",
    "29":"29",
    "30":"30",
    "31":"31",
    "32":"32",
    "33":"33",
    "34":"34",
    "35":"35",
    "柔性振盘动作流程":"Paramètres plateau vibrant (PV)",
    "振盘动作组合":"Combinaison de mouvements PV",
    "动作类型":"Type d'action: ",
    "持续时长":"Durée",
    "动作设置":"Paramètres",
    "写入":"Enreg.",
    "运行":"Exécuter",
    "注\n数据更改后，需要先【写入】，然后才能够执行【背光开】、【背光关】、以及【运行】等动作。":"Remarque : \nAprès avoir modifié les données, vous devez d'abord les [Enreg.] avant de pouvoir exécuter les actions [Lumière ON], [Lumière OFF] et [Exécuter].",
    "光源开":"Lumière ON",
    "光源关":"Lumière OFF",
    "2#柔振":"2# Vib",
    "ms":" ms",
    "mm":" mm",
    "mm/s":" mm/s",
    "mm/ss":" mm/ss",
    "散开":"Disperser",
    "横":"Horizontal",
    "竖":"Vertical",
    "左":"Gauche",
    "下":"Bas",
    "上":"Haut",
    "右":"Droite",
    "动作设置 - 散开":"Action - Disperser",
    "动作设置 - 右上":"Action - Haut Droite",
    "动作设置 - 右下<":"Action - Bas Droite",
    "动作设置 - 左上":"Action - Haut Gauche",
    "动作设置 - 左下":"Action - Bas Gauche",
    "动作设置 - 上":"Action - Haut",
    "动作设置 - 下":"Action - Bas",
    "动作设置 - 右":"Action - Droite",
    "动作设置 - 竖":"Action - Vertical",
    "动作设置 - 左":"Action - Gauche",
    "动作设置 - 横":"Action - Horizontal",
    "2#柔性振盘动作流程":"2# Vib groupe d'action",
    "使用2#振盘":"Utiliser 2# Vib",
    "开启振动":"Vibration ON",
    "关闭振动":"Vibration OFF",
    "振盘单一动作设置":"Paramètres action unitaire PV",
    "柔抓外夹模式":"Mode pince",
    "柔抓内撑模式":"Mode pince interne",
    "兼容模式":"Mode compatibilité",
    "上相机设置":"Paramètres caméra",
    "相机坐标系":"Système de coordonnées caméra",
    "动作类型 - ":"Type d'action - ",
    "左上":"Haut Gauche",
    "左下":"Bas Gauche",
    "右上":"Haut Droite",
    "右下":"Bas Droite",
    "次":" Temps",
    "摆盘":"Palettisation simple",
    "分拣":"Triage",
    "连机":"Machine connectée",
    "自由托盘":"Dépose libre",
    "自由摆盘":"Dépose libre",
    "多种物料摆盘":"Palettisation de plusieurs types de pièces",
    "CAD摆盘":"Palettisation CAO",
    "日志":"log",
    "关闭":"Fermer",
    "亮度":"Luminosité: ",
    "移动到拍照位置":"Position Capt.",
    "拍摄":"Capt",
    "确定":"OK",
    "完成(&amp;F)":"&Fin",
    "完成":"Fin",
    "错误":"Erreur",
    "身份":"Utilisateur: ",
    "进入":"Entrer",
    "限制值设置":"Config limites",
    "阴影 &lt; 加料面积则加料":"Ombre &lt; Zone d'alimentation",
    "加料面积":"Surface d'alimentation: ",
    "1#料仓控制":"1# Silo",
    "2#料仓控制":"2# Silo",
    "Blob设置":"Param Blob",
    "不良位置":"Mauvaise pos",
    "使用振盘阴影检测":"Utilisation détection d'ombres par vibration",
    "振盘阴影检测":"Détection d'ombres par vibration",
    "Blob面积结果":"Résultat surface Blob",
    "Blob阴影面积总值为： %1\n点击【是】将面积值写入到【加料面积】中。":"La valeur totale de la zone d'ombre du blob est: %1\nCliquez sur [Oui] pour sauvegarder la valeur.",
    "是":"Oui",
    "模版编号":"Numéro Modèle: ",
    "物料模版编号":"Numéro Template",
    "否":"Non",
    "料仓设置":"Paramètres Silo",
    "使用料仓":"Utiliser Silo",
    "类型":"Type",
    "IO料仓":"E/S Silo",
    "客制料仓":"Silo sur mesure",
    "加料时长":"Temps d'alim: ",
    "加料条件":"Condition d'alim: ",
    "吹气前延时":"Délai avant vibration",
    "吹气后延时":"Délai après vibration",
    "识别数&lt; ":"Nbr &lt; ",
    "开机复位":"Réinit. au démarrage",
    "移动到待机位置":"Position Capt",
    "复位后到待机位置":"Position Capt après réinit.",
    "复位周期":"Période réinit.",
    "各轴偏移量":"Offset",
    "M1":"M1: ",
    "M2":"M2: ",
    "M3":"M3: ",
    "M1 轴：":"M1: ",
    "M2 轴：":"M2: ",
    "M3 轴：":"M3: ",
    "修改数值":"Modifier valeur",
    "R轴有原点开关":"L'axe R est équipé d'un interrupteur d'origine.",
    "轨迹参数":"Param. trajectoire",
    "半径":"Rayon: ",
    "振后延时":"Retard AV: ",
    "放料后平移":"Déplacement horiz. après dépose",
    "X方向距离":"Dist X: ",
    "Y方向距离":"Dist Y:",
    "取放模式":"Param. Pick/Place",
    "放料许可":"Permis dépose",
    "R轴可以旋转360°":"Rotation axe R à 360°",
    "料满直接启动":"Démarr. directement",
    "开机托盘清空":"Vider le plateau de démarr.",
    "真空检测":"Contrôle vide",
    "延迟时间":"Retard: ",
    "吸取失败时重新拍照":"Reprendre photos en cas d'échec",
    "待机位置":"Position Capt",
    "Goto":"Aller à",
    "吸取不良放置位置":"Position NG",
    "吸咀清理时长":"Durée nettoyage ventouse: ",
    "抓取设置":"Param. Prise",
    "释放设置":"Param. Dépose",
    "抓取延时":"Délai Prise",
    "释放动作延时":"Délai Dépose",
    "抓取缓冲":"Buffer Prise",
    "释放缓冲":"Buffer Dépose",
    "距离":"Dist: ",
    "速度":"Vit: ",
    "不提前放料":"Ne pas décharger à l'avance",
    "接用户信号释放":"Déclench. signal utilisateur",
    "取放模式":"Mode Pick/Place",
    "使用破真空":"Soufflage Dépose",
    "附加延时":"Délai add: ",
    "真空夹抓逻辑取反":"Inversion Y0",
    "一抓一拍":"Capt à chaque Prise",
    "拍照延时":"Délai Capt",
    "取放料模式设置":"Réglage mode de Prise et de Dépose",
    "放料托盘坐标系":"Dépose coor",
    "自由摆盘外盘":"Palette ext",
    "中层托盘":"Palette mil",
    "内层托盘":"Palette int",
    "行数":"Nbr ligne: : ",
    "行距":"Dist ligne: ",
    "列距":"Dist col: ",
    "列数":"Nbr col: ",
    "托盘放置延时":"Délai Dépose",
    "层数":"Nbr couche: ",
    "层距":"Dist couche: ",
    "一行一列一层时输出料满信号":"Sortie signal tjr complète",
    "整盘时不拍照":"Pas de Capt pendant un cycle",
    "托盘坐标系":"Coordonnée palette",
    "按输入口指示放料":"Dépose avec signal X...",
    "X方向偏移距离":"Dist. décalage direction X: ",
    "Y方向偏移距离":"Dist. décalage direction Y: ",
    "按X20,X21,X22,X23,X24放料":"Dépose avec X20,X21,X22,X23,X24",
    "基本信息":"Informations de base",
    "收集用于创建托盘坐标系的基本信息，并且根据这些信息来生成托盘坐标系。":"    Collecter les informations de base nécessaires à la création du système de coordonnées de la palette et générer ce système à partir de ces informations.",
    "托盘坐标系的创建采用两点法：\n1、第一点用于设置原点坐标；\n2、第二点用于设置X轴正方向。":"La création du système de coordonnées du plateau s'effectue à l'aide de la méthode des deux points :\n    1. Le premier point sert à définir les coordonnées du point d'origine ;\n    2. Le deuxième point sert à définir la direction positive de l'axe X.",
    "抓取":"Saisir",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘左下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的原点设置。":"Cliquez sur le bouton [Appr.] pour ouvrir la fenêtre d'enseignement du robot.\n    Ajustez la position du robot afin qu'il soit aligné avec l'emplacement de dépose dans le coin inférieur gauche du plateau.\n    Cliquez sur le bouton [OK] dans la fenêtre d'enseignement pour terminer le réglage de l'origine du système de coordonnées du plateau.",
    "托盘左下角":"Coin Inférieur Gauche du plateau",
    "上一步(&amp;L)":"&Préc.",
    "下一步(&amp;N)":"&Suiv.",
    "X轴正方向设置":"Réglage de la direction positive de l'axe X",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘右下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的X轴正方向设置。":"Cliquez sur le bouton [Appr.] pour ouvrir la fenêtre d'enseignement du robot.\n    Ajustez la position du robot afin qu'il soit aligné avec l'emplacement de dépose dans le coin inférieur droit du plateau.\n    Cliquez sur le bouton [OK] dans la fenêtre d'enseignement pour terminer le réglage de l'axe X positif du système de coordonnées du plateau.",
    "托盘右下角":"Coin Inférieur Droit du plateau",
    "信息收集完成":"La collecte d'informations est terminée.",
    "用于创建托盘坐标系的信息已经收集完成。\n你可以点击【完成】按钮进行坐标系的计算。\n如果需要更改某些参数，也可以点击【上一步】按钮，进行参数更改。":"Les informations nécessaires à la création du système de coordonnées de la palette ont été collectées.\n    Vous pouvez cliquer sur le bouton [Fin] pour calculer le système de coordonnées.\n    Si vous souhaitez modifier certains paramètres, vous pouvez également cliquer sur le bouton [Préc.] pour les modifier.",
    "注意：\n如果你在这里点击【完成】按钮对托盘坐标系进行了修改，则必然会影响到取放料的位置。因而必须重新设置取放料位置，否则会出现放料位置偏差的问题。":"Remarque :\n    Si vous cliquez ici sur le bouton [Fin] pour modifier le système de coordonnées du plateau, cela aura nécessairement une incidence sur la position de chargement et de déchargement. Il est donc nécessaire de redéfinir la position de chargement et de déchargement, sinon cela entraînera un décalage de la position de déchargement.",
    "抓取动作延时":"Délai Prise",
    "W(背)":"B ",
    "G(上)":"H ",
    "编辑":"Modifier",
    "警告":"Avertissement",
    "绘制":"Dessiner",
    "硬触发":"Déclencheur manuel",
    "移动到识别点":"Aller au point d'identification",
    "提升":"Lever la pièce",
    "放料首位置":"Première Pos. palette",
    "轨迹半径":"Rayon: ",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘左下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的原点设置。":"Cliquez sur le bouton [Appr.] pour ouvrir la fenêtre d'enseignement du robot.\n    Ajustez la position du robot afin qu'elle soit positionnée dans le coin inférieur gauche du plateau.\n    Cliquez sur le bouton [OK] dans la fenêtre d'enseignement pour terminer le paramètre d'origine du système de coordonnées du plateau.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第二个特征点：P2。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。":"Cliquez sur le bouton [Appr.] pour ouvrir la fenêtre d'enseignement.\n    Ajustez le robot pour l'aligner avec le deuxième point de fonctionnalité sur la carte d'étalonnage: P2.\n    Cliquez ensuite sur le bouton [OK] de la fenêtre d'enseignement pour lire la position actuelle du robot.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第一个特征点：P1。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。":"Cliquez sur le bouton [Appr.] pour ouvrir la fenêtre d'enseignement.\n    Ajustez le robot pour l'aligner avec le premier point de fonctionnalité sur la carte d'étalonnage: P1.\n    Cliquez ensuite sur le bouton [OK] de la fenêtre d'enseignement pour lire la position actuelle du robot.",
    "轻摇皮带手柄，使标定板随皮带在采样位置的基础上，继续向前移动一段距离（在保证机器人能够采样到P1点的条件下，移动尽可能远的距离）。\n点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第二个特征点：P1。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。":"Secouez doucement la poignée de la courroie de sorte que la plaque d'étalonnage continue d'avancer sur une distance en fonction de la position d'échantillonnage avec la courroie (pour se déplacer autant que possible tout en veillant à ce que le robot puisse échantillonner pour pointer P1).\n    Cliquez sur le bouton [Appr.] pour ouvrir la fenêtre d'enseignement.\n    Ajustez le robot pour l'aligner avec le deuxième point de fonctionnalité sur la carte d'étalonnage: P1.\n    Cliquez ensuite sur le bouton [OK] de la fenêtre d'enseignement pour lire la position actuelle du robot.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使机器人上的工件样品对准托盘最左下角的放料位置。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。":"Cliquez sur le bouton [Appr.] pour ouvrir la fenêtre d'enseignement.\n    Ajustez le robot afin que l'échantillon de pièce sur le robot soit aligné avec la position de décharge dans le coin inférieur gauche du plateau.\n    Cliquez ensuite sur le bouton [OK] de la fenêtre d'enseignement pour lire la position actuelle du robot.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准柔性振盘上的工件样品。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。":"Cliquez sur le bouton [Appr.] pour ouvrir la fenêtre d'enseignement.\n    Ajustez le robot pour l'aligner avec l'échantillon de pièce sur le disque flexible.\n    Cliquez ensuite sur le bouton [OK] de la fenêtre d'enseignement pour lire la position actuelle du robot.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准再定位位置。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。":"Cliquez sur le bouton [Appr.] pour ouvrir la fenêtre d'enseignement.\n    Ajustez le robot pour l'aligner sur la position de repositionnement.\n    Cliquez ensuite sur le bouton [OK] de la fenêtre d'enseignement pour lire la position actuelle du robot.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准柔性振盘上的工件样品。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。":"Cliquez sur le bouton [Appr.] pour ouvrir la fenêtre d'enseignement.\n    Ajustez le robot pour l'aligner avec l'échantillon de pièce sur le disque flexible.\n    Cliquez ensuite sur le bouton [OK] de la fenêtre d'enseignement pour lire la position actuelle du robot.",
    "在镜头下发现 %1 个元件样品。但是系统要求只能够放置一个。\n\n请你在确保镜头下方只有一个元件样品的情况下，再次识别。":"%1 échantillon de composant trouvé sous la lentille. Cependant, le système exige qu'un seul échantillon puisse être placé.\n\nVeuillez l'identifier à nouveau, à condition qu'il n'y ait qu'un seul échantillon de composant sous la lentille.",
    "图上点位编号": "^Nombre de points: ",
    "元件样品识别成功": "Identification réussie de la pièce",
    "元件样品识别失败": "Échec de l'identification de la pièce",
    "P:": "P ",
    "R:": "R:",
    "X:": "X:",
    "Y::": "Y:",
    "Z::": "Z:",
    "注：\n在每一次更换产品时，都需要进行一次取放位置的采样。": "Remarque :\n    À chaque changement de pièce, il est nécessaire de procéder à un recalibrage de la position de prise et de dépose.",
    "样品放置": "Placement des pièces",
    "取料位样品识别": "Identification des pièces à la hauteur de prise",
    "点击下面的【提升】按钮，机器人自动提升到待机位置高度。\n": "    Cliquez sur le bouton [Lever la pièce] ci-dessous pour que le robot s'élève automatiquement à la hauteur de la Position Capt. .",
    "位置采样": "Échantillonnage",
    "点击下面的【释放】按钮，吸盘或者是夹抓上的工件将会释放到托盘中。\n在释放完成后，点击【下一步】执行后续步骤。": "Cliquez sur le bouton [Libérer] ci-dessous pour libérer la pièce fixée à la ventouse ou à la pince sur le plateau.\nUne fois la libération terminée, cliquez sur [Suiv.] pour passer à l'étape suivante.",
    "释放": "Libérer",
    "取放位置采样": "Échantillonnage Pick et place",
    "识别": "Identification",
    "点击【移动到识别点】按钮，机器人会移动到上一步所识别的样品位置。\n需要注意的是，在这里目标位置的Z值坐标并不是准确的。\n抓取的具体位置，你仍然可以在下一步进行设置。": "    Cliquez sur le bouton [Aller au point d'identification] pour que le robot se déplace vers l'emplacement de la pièce identifié à l'étape précédente.\n    Il est important de noter que la coordonnée Z de l'emplacement cible n'est pas exacte à ce stade.\n    Vous pourrez toujours définir l'emplacement exact de la préhension à l'étape suivante.",
    "R": "R",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    " s": " s",
    "第": "Le",
    "侧面安装": "Installation latérale",
    "位号块大小": "Taille du bloc d'adresse: ",
    "料位个数": "Nombre de niveaux de remplissage: ",
}