manual_dict = {
    "加料时长": "Zuführdauer:",
    "温度": "Temperatur:",
    "速度": "Geschwindigkeit:",
    "进料": "Teilezufuhr",
    "出料": "Teileabfuhr",
    "+": "+",
    "-": "-",
    "%": "%",
    "s": " s",
    "个": " Stk.",
    "频率": "Frequenz:",
    "振幅": "Amplitude:",
    "中文（中国）": "Chinesisch",
    "English": "Englisch",
    "动作、速度设置": "Aktion, Geschw.",
    "原点设置": "Ursprungseinstellung",
    "轨迹相关": "Bahnbezogen",
    "托盘参数": "Palettenparameter",
    "取放位置": "Pick-und-Place-Position",
    "柔性振盘方式": "Vibrationsplattenmethode",
    "供料方式": "Zuführungsart:",
    "设备动作类型": "Gerätetypaktion:",
    "相机设置": "Kameraeinstellungen",
    "相机设置2": "Kameraeinstellungen 2",
    "保存": "Speichern",
    "恢复": "Wiederherstellen",
    "单轴速度、软极限设置": "Einachsgeschwindigkeit, Softwarelimit-Einstellung",
    "XYZ软极限": "XYZ Softwarelimit",
    "机器人速度设置": "Robotergeschwindigkeitseinstellungen",
    "使用下相机": "Unterkamera verwenden",
    "使用放料位相机": "Kamera für Platzierungsposition verwenden",
    "柔触切换": "Greifertyp:",
    "吸盘模式": "Saugnapfmodus",
    "扩展设备": "Erweiterungsgeräte:",
    "无": "Keine",
    "真空吸取失败限制次数": "Max. Anzahl der Saugfehler:",
    "方案保存": "Projekt speichern",
    "系统相关": "Systeminformationen",
    "版本信息": "Versionsinformationen",
    "视觉方案": "Visuelles Schema",
    "全局控件": "Globale Steuerung",
    "返回": "Zurück",
    "主程序未启动，未运行": "Hauptprogramm inaktiv, bereit zum Start",
    "清零": "Zurücksetzen",
    "产量": "Produktion:",
    "计数": "Zählung:",
    "取放计时": "Pick-und-Place-Zeit:",
    "托盘计时": "Palettenzeit:",
    "月运行秒": "Sekunden/Monat:",
    "日": "Tag",
    "内托盘行": "Innere Palettenreihe",
    "中托盘行": "Mittlere Palettenreihe",
    "外盘行": "Äußere Palettenreihe",
    "外托盘行": "Äußere Palettenreihe",
    "托盘层": "Palettenebene",
    "Delta装盘机器人 -": "Delta-Palettierroboter - MA-R1 -",
    "打开": "Öffnen",
    "另存为": "Speichern unter",
    "保存": "Speichern",
    "设置": "Param.",
    "示教": "Lehren",
    "复位(&R)": "&Zurücks.",
    "启动(&S)": "&Start",
    "暂停(&P)": "&Pause",
    "停止(&T)": "&Stopp",
    "软件重启": "Software-Neustart",
    "新开打的文件，需要重新启动软件才起作用。请点击【确定】关闭软件后，重启软件。": "Neu geöffnete Dateien erfordern einen Neustart der Software, um wirksam zu werden. Bitte klicken Sie auf [OK], um die Software zu schließen und neu zu starten.",
    "确定(&O)": "&OK",
    "设置权限": "Berechtigungen einstellen",
    "请输入密码": "Bitte Passwort eingeben",
    "密码": "Passwort:",
    "取消(&C)": "&Abbrechen",
    "机器人运行速度设置": "Robotergeschwindigkeitseinstellung",
    "运行-最高速度": "Max. Geschwindigkeit:",
    "运行-加速度": "Beschleunigung:",
    "R轴半径": "R-Achsen-Radius:",
    "圆弧速度系数": "Tangentialgeschwindigkeitskoeffizient:",
    "IO操作": "I/O-Bedienung",
    "/": "/",
    " / ": " / ",
    "列": "Spalte",
    "清\n空": "L\nE\nE\nR",
    "清\n除": "L\nE\nE\nR",
    "历\n史": "V\nE\nR\nL\nA\nU\nF",
    "日\n志": "P\nR\nO\nT\nO\nK\nO\nL\nL",
    "当前轴： M1 轴": "Aktuelle Achse: M1-Achse",
    "当前轴： M2 轴": "Aktuelle Achse: M2-Achse",
    "当前轴： M3 轴": "Aktuelle Achse: M3-Achse",
    "当前轴： M4 轴": "Aktuelle Achse: M4-Achse",
    "当前轴： M5 轴": "Aktuelle Achse: M5-Achse",
    "当前轴： M6 轴": "Aktuelle Achse: M6-Achse",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "23": "23",
    "24": "24",
    "25": "25",
    "26": "26",
    "27": "27",
    "28": "28",
    "29": "29",
    "30": "30",
    "31": "31",
    "32": "32",
    "33": "33",
    "34": "34",
    "35": "35",
    "柔性振盘动作流程": "Ablauf der Vibrationsplatte (PV)",
    "振盘动作组合": "Kombination der Vibrationsbewegungen",
    "动作类型": "Aktionstyp:",
    "持续时长": "Dauer",
    "动作设置": "Einstellungen",
    "写入": "Speichern",
    "运行": "Ausführen",
    "注\n数据更改后，需要先【写入】，然后才能够执行【背光开】、【背光关】、以及【运行】等动作。": "Hinweis:\nNach der Datenänderung müssen Sie zuerst [Speichern], bevor Sie Aktionen wie [Hintergrundlicht ein], [Hintergrundlicht aus] und [Ausführen] durchführen können.",
    "光源开": "Licht ein",
    "光源关": "Licht aus",
    "2#柔振": "2# Vib",
    "ms": " ms",
    "mm": " mm",
    "mm/s": " mm/s",
    "mm/ss": " mm/ss",
    "散开": "Verteilen",
    "横": "Horizontal",
    "竖": "Vertikal",
    "左": "Links",
    "下": "Unten",
    "上": "Oben",
    "右": "Rechts",
    "动作设置 - 散开": "Aktion - Verteilen",
    "动作设置 - 右上": "Aktion - Oben Rechts",
    "动作设置 - 右下": "Aktion - Unten Rechts",
    "动作设置 - 左上": "Aktion - Oben Links",
    "动作设置 - 左下": "Aktion - Unten Links",
    "动作设置 - 上": "Aktion - Oben",
    "动作设置 - 下": "Aktion - Unten",
    "动作设置 - 右": "Aktion - Rechts",
    "动作设置 - 竖": "Aktion - Vertikal",
    "动作设置 - 左": "Aktion - Links",
    "动作设置 - 横": "Aktion - Horizontal",
    "2#柔性振盘动作流程": "2# Vib Aktionsgruppe",
    "使用2#振盘": "2# Vib verwenden",
    "开启振动": "Vibration EIN",
    "关闭振动": "Vibration AUS",
    "振盘单一动作设置": "Einzelaktionseinstellungen PV",
    "柔抓外夹模式": "Modus äußere Klemme",
    "柔抓内撑模式": "Modus innere Stütze",
    "兼容模式": "Kompatibilitätsmodus",
    "上相机设置": "Einstellungen obere Kamera",
    "相机坐标系": "Kamerakoordinatensystem",
    "动作类型 - ": "Aktionstyp - ",
    "左上": "Oben Links",
    "左下": "Unten Links",
    "右上": "Oben Rechts",
    "右下": "Unten Rechts",
    "次": " Mal",
    "摆盘": "Einfache Palettierung",
    "分拣": "Sortieren",
    "连机": "Maschine verbunden",
    "自由托盘": "Freie Platzierung",
    "自由摆盘": "Freie Platzierung",
    "多种物料摆盘": "Palettierung mehrerer Teiletypen",
    "CAD摆盘": "CAD-Palettierung",
    "日志": "Protokoll",
    "关闭": "Schließen",
    "亮度": "Helligkeit:",
    "移动到拍照位置": "Zur Aufnahmeposition bewegen",
    "拍摄": "Aufnahme",
    "确定": "OK",
    "完成(&F)": "&Fertig",
    "完成": "Fertig",
    "错误": "Fehler",
    "身份": "Benutzer:",
    "进入": "Eingabe",
    "限制值设置": "Grenzwerte einstellen",
    "阴影 &lt; 加料面积则加料": "Schatten &lt; Füllbereich",
    "加料面积": "Füllbereich:",
    "1#料仓控制": "1# Bunker",
    "2#料仓控制": "2# Bunker",
    "Blob设置": "Blob-Einstellungen",
    "不良位置": "Schlechte Position",
    "使用振盘阴影检测": "Vibration-Schatten-Erkennung verwenden",
    "振盘阴影检测": "Vibration-Schatten-Erkennung",
    "Blob面积结果": "Blob-Flächenergebnis",
    "Blob阴影面积总值为： %1\n点击【是】将面积值写入到【加料面积】中。": "Der Gesamtwert der Blob-Schattenfläche beträgt: %1\nKlicken Sie auf [Ja], um den Wert zu speichern.",
    "是": "Ja",
    "模版编号": "Modellnummer:",
    "物料模版编号": "Materialvorlagennummer",
    "否": "Nein",
    "料仓设置": "Bunkereinstellungen",
    "使用料仓": "Bunker verwenden",
    "类型": "Typ",
    "IO料仓": "I/O-Bunker",
    "客制料仓": "Kundenspezifischer Bunker",
    "加料时长": "Fülldauer:",
    "加料条件": "Füllbedingung:",
    "吹气前延时": "Verzögerung vor Vibration",
    "吹气后延时": "Verzögerung nach Vibration",
    "识别数&lt;": "Anzahl &lt;",
    "开机复位": "Zurücksetzen beim Start",
    "移动到待机位置": "Zur Bereitschaftsposition bewegen",
    "复位后到待机位置": "Zur Bereitschaftsposition nach Rücksetzung",
    "复位周期": "Rücksetzzyklus",
    "各轴偏移量": "Achsenversatz",
    "M1": "M1:",
    "M2": "M2:",
    "M3": "M3:",
    "M1 轴：": "M1-Achse:",
    "M2 轴：": "M2-Achse:",
    "M3 轴：": "M3-Achse:",
    "修改数值": "Wert ändern",
    "R轴有原点开关": "Die R-Achse ist mit einem Ursprungsschalter ausgestattet.",
    "轨迹参数": "Bahnparameter",
    "半径": "Radius:",
    "振后延时": "Verzögerung nach Vibration:",
    "放料后平移": "Horizontalverschiebung nach Platzierung",
    "X方向距离": "X-Abstand:",
    "Y方向距离": "Y-Abstand:",
    "取放模式": "Pick-and-Place-Modus",
    "放料许可": "Platzierungsgenehmigung",
    "R轴可以旋转360°": "R-Achse 360° Drehung",
    "料满直接启动": "Direkter Start bei vollem Material",
    "开机托盘清空": "Tablett bei Start leeren",
    "真空检测": "Vakuumprüfung",
    "延迟时间": "Verzögerungszeit:",
    "吸取失败时重新拍照": "Bei Fehlschlag erneut aufnehmen",
    "待机位置": "Bereitschaftsposition",
    "Goto": "Gehe zu",
    "吸取不良放置位置": "NG-Position",
    "吸咀清理时长": "Dauer der Düsenreinigung:",
    "抓取设置": "Greifeinstellungen",
    "释放设置": "Freigabeeinstellungen",
    "抓取延时": "Greifverzögerung",
    "释放动作延时": "Freigabeverzögerung",
    "抓取缓冲": "Greifpuffer",
    "释放缓冲": "Freigabepuffer",
    "距离": "Distanz:",
    "速度": "Geschwindigkeit:",
    "不提前放料": "Nicht vorzeitig freigeben",
    "接用户信号释放": "Freigabe bei Benutzersignal",
    "取放模式": "Pick-and-Place-Modus",
    "使用破真空": "Vakuumbruch bei Freigabe verwenden",
    "附加延时": "Zusätzliche Verzögerung:",
    "真空夹抓逻辑取反": "Invertierung Y0",
    "一抓一拍": "Aufnahme bei jedem Greifen",
    "拍照延时": "Aufnahmeverzögerung",
    "取放料模式设置": "Einstellung des Pick-and-Place-Modus",
    "放料托盘坐标系": "Platzierungskoordinaten",
    "自由摆盘外盘": "Externe Palette",
    "中层托盘": "Mittlere Palette",
    "内层托盘": "Innere Palette",
    "行数": "Anzahl der Reihen:",
    "行距": "Reihenabstand:",
    "列距": "Spaltenabstand:",
    "列数": "Anzahl der Spalten:",
    "托盘放置延时": "Platzierungsverzögerung",
    "层数": "Anzahl der Ebenen:",
    "层距": "Ebenenabstand:",
    "一行一列一层时输出料满信号": "Immer vollständiges Signal ausgeben",
    "整盘时不拍照": "Keine Aufnahme während eines vollständigen Zyklus",
    "托盘坐标系": "Palettenkoordinatensystem",
    "按输入口指示放料": "Platzierung mit Signal X...",
    "X方向偏移距离": "X-Richtungs-Versatzabstand:",
    "Y方向偏移距离": "Y-Richtungs-Versatzabstand:",
    "按X20,X21,X22,X23,X24放料": "Platzierung mit X20, X21, X22, X23, X24",
    "基本信息": "Grundinformationen",
    "收集用于创建托盘坐标系的基本信息，并且根据这些信息来生成托盘坐标系。": "Grundinformationen zur Erstellung des Palettenkoordinatensystems sammeln und das System basierend auf diesen Informationen generieren.",
    "托盘坐标系的创建采用两点法：\n1、第一点用于设置原点坐标；\n2、第二点用于设置X轴正方向。": "Das Palettenkoordinatensystem wird mit der Zwei-Punkte-Methode erstellt:\n1. Der erste Punkt dient zur Festlegung der Ursprungskoordinaten;\n2. Der zweite Punkt dient zur Festlegung der positiven X-Achsenrichtung.",
    "抓取": "Greifen",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘左下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的原点设置。": "Klicken Sie auf die Schaltfläche [Lehren], um das Roboterlehrfenster zu öffnen.\nPassen Sie die Position des Roboters an, sodass er auf die Ablageposition in der unteren linken Ecke des Tabletts ausgerichtet ist.\nKlicken Sie auf die Schaltfläche [OK] im Lehrfenster, um die Ursprungseinstellung des Tablettkoordinatensystems abzuschließen.",
    "托盘左下角": "Untere linke Ecke des Tabletts",
    "上一步(&L)": "&Zurück",
    "下一步(&N)": "&Weiter",
    "X轴正方向设置": "Einstellung der positiven X-Achsenrichtung",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘右下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的X轴正方向设置。": "Klicken Sie auf die Schaltfläche [Lehren], um das Roboterlehrfenster zu öffnen.\nPassen Sie die Position des Roboters an, sodass er auf die Ablageposition in der unteren rechten Ecke des Tabletts ausgerichtet ist.\nKlicken Sie auf die Schaltfläche [OK] im Lehrfenster, um die Einstellung der positiven X-Achsenrichtung des Tablettkoordinatensystems abzuschließen.",
    "托盘右下角": "Untere rechte Ecke des Tabletts",
    "信息收集完成": "Informationssammlung abgeschlossen",
    "用于创建托盘坐标系的信息已经收集完成。\n你可以点击【完成】按钮进行坐标系的计算。\n如果需要更改某些参数，也可以点击【上一步】按钮，进行参数更改。": "Die Informationen zur Erstellung des Tablettkoordinatensystems wurden gesammelt.\nSie können auf die Schaltfläche [Fertig] klicken, um das Koordinatensystem zu berechnen.\nWenn Sie bestimmte Parameter ändern müssen, können Sie auch auf die Schaltfläche [Zurück] klicken, um die Parameter zu ändern.",
    "注意：\n如果你在这里点击【完成】按钮对托盘坐标系进行了修改，则必然会影响到取放料的位置。因而必须重新设置取放料位置，否则会出现放料位置偏差的问题。": "Hinweis:\nWenn Sie hier auf die Schaltfläche [Fertig] klicken, um das Tablettkoordinatensystem zu ändern, wird dies zwangsläufig die Position der Pick-and-Place-Aktion beeinflussen. Daher müssen Sie die Pick-and-Place-Position neu einstellen, andernfalls tritt ein Problem mit der Ablagepositionsabweichung auf.",
    "抓取动作延时": "Greifaktionsverzögerung",
    "W(背)": "H",
    "G(上)": "O",
    "编辑": "Bearbeiten",
    "警告": "Warnung",
    "绘制": "Zeichnen",
    "硬触发": "Manueller Trigger",
    "移动到识别点": "Zum Identifikationspunkt bewegen",
    "提升": "Anheben",
    "放料首位置": "Erste Palettenposition",
    "轨迹半径": "Radius:",
    "点击【示教】按钮，打开机器人示教窗口。\n调整机器人位置，使其对准托盘左下角的放料位置。\n点击示教窗口上的【确定】按钮，即可完成托盘坐标系的原点设置。": "Klicken Sie auf die Schaltfläche [Lehren], um das Roboterlehrfenster zu öffnen.\nPassen Sie die Position des Roboters an, sodass er auf die Ablageposition in der unteren linken Ecke des Tabletts ausgerichtet ist.\nKlicken Sie auf die Schaltfläche [OK] im Lehrfenster, um die Ursprungseinstellung des Tablettkoordinatensystems abzuschließen.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第二个特征点：P2。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Klicken Sie auf die Schaltfläche [Lehren], um das Lehrfenster zu öffnen.\nPassen Sie den Roboter an, sodass er auf den zweiten Merkmalspunkt auf der Kalibrierplatte ausgerichtet ist: P2.\nKlicken Sie dann auf die Schaltfläche [OK] im Lehrfenster, um die aktuelle Position des Roboters zu lesen.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第一个特征点：P1。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Klicken Sie auf die Schaltfläche [Lehren], um das Lehrfenster zu öffnen.\nPassen Sie den Roboter an, sodass er auf den ersten Merkmalspunkt auf der Kalibrierplatte ausgerichtet ist: P1.\nKlicken Sie dann auf die Schaltfläche [OK] im Lehrfenster, um die aktuelle Position des Roboters zu lesen.",
    "轻摇皮带手柄，使标定板随皮带在采样位置的基础上，继续向前移动一段距离（在保证机器人能够采样到P1点的条件下，移动尽可能远的距离）。\n点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准标定板上的第二个特征点：P1。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Schütteln Sie den Riemengriff leicht, sodass die Kalibrierplatte zusammen mit dem Riemen von der Probenentnahmeposition aus weiter nach vorne bewegt (bewegen Sie sie so weit wie möglich, während Sie sicherstellen, dass der Roboter die Probe zum Punkt P1 entnehmen kann).\nKlicken Sie auf die Schaltfläche [Lehren], um das Lehrfenster zu öffnen.\nPassen Sie den Roboter an, sodass er auf den zweiten Merkmalspunkt auf der Kalibrierplatte ausgerichtet ist: P1.\nKlicken Sie dann auf die Schaltfläche [OK] im Lehrfenster, um die aktuelle Position des Roboters zu lesen.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使机器人上的工件样品对准托盘最左下角的放料位置。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Klicken Sie auf die Schaltfläche [Lehren], um das Lehrfenster zu öffnen.\nPassen Sie den Roboter an, sodass die Werkstückprobe auf dem Roboter auf die Ablageposition in der unteren linken Ecke des Tabletts ausgerichtet ist.\nKlicken Sie dann auf die Schaltfläche [OK] im Lehrfenster, um die aktuelle Position des Roboters zu lesen.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准柔性振盘上的工件样品。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Klicken Sie auf die Schaltfläche [Lehren], um das Lehrfenster zu öffnen.\nPassen Sie den Roboter an, sodass er auf die Werkstückprobe auf der flexiblen Vibrationsplatte ausgerichtet ist.\nKlicken Sie dann auf die Schaltfläche [OK] im Lehrfenster, um die aktuelle Position des Roboters zu lesen.",
    "点击【示教】按钮，打开示教窗口。\n调整机器人，使其对准再定位位置。\n然后点击示教窗口上的【确定】按钮，读取机器人的当前位置。": "Klicken Sie auf die Schaltfläche [Lehren], um das Lehrfenster zu öffnen.\nPassen Sie den Roboter an, sodass er auf die Neupositionierungsposition ausgerichtet ist.\nKlicken Sie dann auf die Schaltfläche [OK] im Lehrfenster, um die aktuelle Position des Roboters zu lesen.",
    "在镜头下发现 %1 个元件样品。但是系统要求只能够放置一个。\n\n请你在确保镜头下方只有一个元件样品的情况下，再次识别。": "Unter dem Objektiv wurde %1 Bauteilmuster gefunden. Das System erlaubt jedoch nur die Platzierung eines einzigen Musters.\n\nBitte identifizieren Sie erneut und stellen Sie sicher, dass sich nur ein Bauteilmuster unter dem Objektiv befindet.",
    "图上点位编号": "Punktnummer auf dem Bild:",
    "元件样品识别成功": "Bauteilmuster erfolgreich erkannt",
    "元件样品识别失败": "Bauteilmustererkennung fehlgeschlagen",
    "P:": "P:",
    "R:": "R:",
    "X:": "X:",
    "Y::": "Y:",
    "Z::": "Z:",
    "注：\n在每一次更换产品时，都需要进行一次取放位置的采样。": "Hinweis:\nBei jedem Produktwechsel muss eine Probenentnahme der Pick-and-Place-Position durchgeführt werden.",
    "样品放置": "Musterplatzierung",
    "取料位样品识别": "Mustererkennung an der Entnahmeposition",
    "点击下面的【提升】按钮，机器人自动提升到待机位置高度。\n": "Klicken Sie auf die Schaltfläche [Anheben] unten, um den Roboter automatisch auf die Höhe der Bereitschaftsposition anzuheben.",
    "位置采样": "Positionsprobenentnahme",
    "点击下面的【释放】按钮，吸盘或者是夹抓上的工件将会释放到托盘中。\n在释放完成后，点击【下一步】执行后续步骤。": "Klicken Sie auf die Schaltfläche [Freigeben] unten, um das Werkstück von der Saugglocke oder dem Greifer auf das Tablett freizugeben.\nNach Abschluss der Freigabe klicken Sie auf [Weiter], um mit dem nächsten Schritt fortzufahren.",
    "释放": "Freigabe",
    "取放位置采样": "Pick-und-Place-Positionsprobenentnahme",
    "识别": "Erkennung",
    "点击【移动到识别点】按钮，机器人会移动到上一步所识别的样品位置。\n需要注意的是，在这里目标位置的Z值坐标并不是准确的。\n抓取的具体位置，你仍然可以在下一步进行设置。": "Klicken Sie auf die Schaltfläche [Zum Identifikationspunkt bewegen], damit sich der Roboter zur Musterposition bewegt, die im vorherigen Schritt erkannt wurde.\nBeachten Sie, dass die Z-Koordinate der Zielposition hier nicht genau ist.\nDie genaue Greifposition können Sie im nächsten Schritt einstellen.",
    "R": "R",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    " s": " s",
    "第": "Der",
    "侧面安装": "Seitliche Installation",
    "位号块大小": "Größe des Adressblocks:",
    "料位个数": "Anzahl der Füllstände:"
}
